import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Djesu',
      email: 'djesu@yahoomail.com',
      password: bcrypt.hashSync('1234', 8),
      isSeller: false,
      isAdmin: true,
    },
    {
      name: 'Selorm',
      email: 'sdzramado@gmail.com',
      password: bcrypt.hashSync('7654', 8),
      isSeller: false,
      isAdmin: true,
    },
    {
      name: 'kofi',
      email: 'kofi@gmail.com',
      password: bcrypt.hashSync('7654', 8),
      isSeller: true,
      isAdmin: false,
    },

    {
      name: 'sammy',
      email: 'sammy@gmail.com',
      password: bcrypt.hashSync('1111', 8),
      isSeller: true,
      isAdmin: false,
    },
  ],
  members: [
    {
      surname: 'Mensah',
      other_names: 'Efua',
      gender: 'Female',
      dob: '08 / 03 / 1998',
      marital_status: 'single',
      telno: '0249221188',
      res_address: 'House No. 25, Spintex Road, Tema',
      occupation: 'Nurse',
      place_of_work: 'Ridge Hospital',
      location_of_work: 'Ridge, Accra',
      emergency_contact_name: 'John Mensah',
      emergency_contact_no: '0234564323',
      description: 'A young and energietic person full of grace and truth',
      image: '/images/passport7.jpg',
      gpAddress: '373-543-123',
    },
    {
      surname: 'Arthur',
      other_names: 'Mary',
      gender: 'Female',
      dob: '08 / 03 / 1998',
      marital_status: 'married',
      telno: '0249221388',
      res_address: 'House No. 71, Spintex Road, Tema',
      occupation: 'Caterer',
      place_of_work: 'McBrowns Kitchen',
      location_of_work: 'Circle, Accra',
      emergency_contact_name: 'John Atta',
      emergency_contact_no: '0234564323',
      description: 'A young and energietic caterer',
      image: '/images/passport2.jpg',
      gpAddress: '373-543-166',
    },
    {
      surname: 'Amissah',
      other_names: 'Adwoa',
      gender: 'Female',
      dob: '08 / 03 / 1993',
      marital_status: 'single',
      telno: '0249221145',
      res_address: 'House No. 83, Spintex Road, Tema',
      occupation: 'Clerk',
      place_of_work: 'Ministry of Education',
      location_of_work: 'Ministries, Accra',
      emergency_contact_name: 'James Abban',
      emergency_contact_no: '0234562323',
      description: 'Good clerk filled with passion',
      image: '/images/passport3.jpg',
      gpAddress: '373-543-120',
    },
    {
      surname: 'Armah',
      other_names: 'Sarah',
      gender: 'Female',
      dob: '08 / 03 / 1978',
      marital_status: 'married',
      telno: '0249221188',
      res_address: 'House No. 25, Nungua, Beach Road.',
      occupation: 'Teacher',
      place_of_work: 'St Johns Primary School',
      location_of_work: 'Teshie, Accra',
      emergency_contact_name: 'John Mensah',
      emergency_contact_no: '0234564327',
      description: 'A young and energietic teacher',
      image: '/images/passport4.jpg',
      gpAddress: '373-543-123',
    },
    {
      surname: 'Effah',
      other_names: 'John',
      gender: 'Male',
      dob: '08 / 03 / 1968',
      marital_status: 'married',
      telno: '0249221154',
      res_address: 'House No. 25, community 2, Tema',
      occupation: 'Banker',
      place_of_work: 'Ecobank',
      location_of_work: 'Ridge, Accra',
      emergency_contact_name: 'John Mensah',
      emergency_contact_no: '0234224323',
      description: 'A young and energietic banker',
      image: '/images/passport5.jpg',
      gpAddress: '373-543-121',
    },
    {
      surname: 'Amuah',
      other_names: 'James',
      gender: 'male',
      dob: '08 / 03 / 1998',
      marital_status: 'single',
      telno: '0249221188',
      res_address: 'House No. 25, Spintex Road, Tema',
      occupation: 'Soldier',
      place_of_work: '37 Military Hospital',
      location_of_work: 'Accra',
      emergency_contact_name: 'John Otu-saah',
      emergency_contact_no: '0234564323',
      description: 'A young and energietic soldier',
      image: '/images/passport6.jpg',
      gpAddress: '373-543-126',
    },
  ],
}
export default data
