export const SMS_MESSAGE_REQUEST = 'SMS_MESSAGE_REQUEST'
export const SMS_MESSAGE_SUCCESS = 'SMS_MESSAGE_SUCCESS'
export const SMS_MESSAGE_FAIL = 'SMS_MESSAGE_FAIL'
export const SMS_MESSAGE_RESET = 'SMS_MESSAGE_RESET'
