export const VISITOR_LIST_REQUEST = 'VISITOR_LIST_REQUEST'
export const VISITOR_LIST_SUCCESS = 'VISITOR_LIST_SUCCESS'
export const VISITOR_LIST_FAIL = 'VISITOR_LIST_FAIL'

export const VISITOR_DETAILS_REQUEST = 'VISITOR_DETAILS_REQUEST'
export const VISITOR_DETAILS_SUCCESS = 'VISITOR_DETAILS_SUCCESS'
export const VISITOR_DETAILS_FAIL = 'VISITOR_DETAILS_FAIL'

export const VISITOR_CREATE_REQUEST = 'VISITOR_CREATE_REQUEST'
export const VISITOR_CREATE_SUCCESS = 'VISITOR_CREATE_SUCCESS'
export const VISITOR_CREATE_FAIL = 'VISITOR_CREATE_FAIL'
export const VISITOR_CREATE_RESET = 'VISITOR_CREATE_RESET'

export const VISITOR_UPDATE_REQUEST = 'VISITOR_UPDATE_REQUEST'
export const VISITOR_UPDATE_SUCCESS = 'VISITOR_UPDATE_SUCCESS'
export const VISITOR_UPDATE_FAIL = 'VISITOR_UPDATE_FAIL'
export const VISITOR_UPDATE_RESET = 'VISITOR_UPDATE_RESET'

export const VISITOR_DELETE_REQUEST = 'VISITOR_DELETE_REQUEST'
export const VISITOR_DELETE_SUCCESS = 'VISITOR_DELETE_SUCCESS'
export const VISITOR_DELETE_FAIL = 'VISITOR_DELETE_FAIL'
export const VISITOR_DELETE_RESET = 'VISITOR_DELETE_RESET'

export const VISITOR_GET_REQUEST = 'VISITOR_GET_REQUEST'
export const VISITOR_GET_SUCCESS = 'VISITOR_GET_SUCCESS'
export const VISITOR_GET_FAIL = 'VISITOR_GET_FAIL'
export const VISITOR_GET_RESET = 'VISITOR_GET_RESET'
